### ISSUE TITLE
Cannot pass arrays to Q# entry points with qsharp.azure.execute.

### ISSUE THREAD

**Issue by cgranade** [microsoft/iqsharp#401]
**Describe the bug**
When passing an array to a Q# entry point with the `qsharp.azure.execute` function, `Object must implement IConvertible` is printed to `channel.Stderr`:

```
Object must implement IConvertible.
Traceback (most recent call last):
File "test.py", line 14, in <module>
result = qsharp.azure.execute([operation-name], [params])
File "/home/[username]/.local/lib/python3.6/site-packages/qsharp/azure.py", line 137, in execute
if "error_code" in result: raise AzureError(result)
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by cgranade** [comment]
This has now been fixed with #398.
