### ISSUE TITLE
CI broken for conda packages on macOS

### ISSUE THREAD

**Issue by cgranade** [microsoft/iqsharp#568]
**Describe the bug**
Currently, per-repo builds of IQ# break on `main` during the macOS conda-build stage. The underlying failure is due to a `DllNotFoundException` when instantiating the full-state simulator:

```
System.AggregateException: One or more errors occurred. (Unable to load shared library 'Microsoft.Quantum.Simulator.Runtime' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(libMicrosoft.Quantum.Simulator.Runtime, 1): image not found)
 ---> System.DllNotFoundException: Unable to load shared library 'Microsoft.Quantum.Simulator.Runtime' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(libMicrosoft.Quantum.Simulator.Runtime, 1): image not found
   at Microsoft.Quantum.Simulation.Simulators.QuantumSimulator.InitNative()
   at Microsoft.Quantum.Simulation.Simulators.QuantumSimulator..ctor(Boolean throwOnReleasingQubitsNotInZeroState, Nullable`1 randomNumberGeneratorSeed, Boolean disableBorrowing)
   at Microsoft.Quantum.IQSharp.Kernel.SimulateMagic.RunAsync(String input, IChannel channel) in /home/vsts/work/1/s/src/Kernel/Magic/Simulate.cs:line 103
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Microsoft.Quantum.IQSharp.Kernel.SimulateMagic.Run(String input, IChannel channel) in /home/vsts/work/1/s/src/Kernel/Magic/Simulate.cs:line 87
   at Microsoft.Quantum.IQSharp.Jupyter.AbstractMagic.RunCancellable(String input, IChannel channel, CancellationToken cancellationToken) in /home/vsts/work/1/s/src/Jupyter/Magic/AbstractMagic.cs:line 182
   at Microsoft.Quantum.IQSharp.Jupyter.AbstractMagic.<>c__DisplayClass2_1.<SafeExecute>b__1() in /home/vsts/work/1/s/src/Jupyter/Magic/AbstractMagic.cs:line 60
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Quantum.IQSharp.Jupyter.AbstractMagic.<>c__DisplayClass2_0.<<SafeExecute>b__0>d.MoveNext() in /home/vsts/work/1/s/src/Jupyter/Magic/AbstractMagic.cs:line 60
```

**To Reproduce**
Start a new CI build for `main`.

**Comment by cgranade** [comment]
@swernli, @kuzminrobin: This looks to be an issue with the recent fix for libomp on the runtime side. While the fix seems to work well on Linux, there may still be a problem on macOS. If we can get a local reproduction, that should give us a bit more information on possible fixes.

**Comment by cgranade** [comment]
An example of a failing build: https://dev.azure.com/ms-quantum-public/Microsoft%20Quantum%20(public)/_build/results?buildId=37071&view=logs&j=ba989ff6-acce-5431-a1a2-7c645ad22444&t=948130ec-5a52-576f-74ec-61f658c3f899

Notably, end-to-end builds still work correctly; @swernli, if I understand right, you'd suggested this is probably because e2e CI configurations add `libomp` to the build agent on macOS?

**Comment by cgranade** [comment]
To try and diagnose the issue, I've run some additional builds with `DYLD_PRINT_LIBRARIES=1`, but it looks like this environment variable may be blocked by SIP on macOS hosts. Locally using the `conda` package produced by the above failing build may be helpful in further diagnosis.
