### ISSUE TITLE
Can't install iqsharp if user's home directory has spaces

### ISSUE THREAD

**Issue by natke** [microsoft/iqsharp#63]
Arguably this is not a bug but a limitation that would not be encountered if best practices were followed (i.e. not creating users, or in fact any filenames, with spaces in them). If so, let us know and we can document this behavior.

**Describe the bug**
When there are spaces in the user's home directory iqsharp cannot be installed, giving errors like the ones shown in this ticket:

https://github.com/MicrosoftDocs/quantum-docs-pr/issues/617

I reproduced the error on a Windows 10 machine, with a user with spaces in the name.

**To Reproduce**
- Create a user with spaces in the name
- Follow the steps here to install the QDK for either the python or jupyter use-case: https://docs.microsoft.com/en-us/quantum/install-guide/?view=qsharp-preview

**Problem**

My Windows10 account folder name is 'C:\Users\Sirius B'.
But when I install it (dotnet iqsharp install), it doesn't recognize 'C:\Users\Sirius B', but it tries to recognize 'C:\Users\Sirius' Perhaps spacing is a problem.

**Error message**

```
C:\Windows\system32>dotnet iqsharp install
Traceback (most recent call last):
File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\runpy.py", line 193, in _run_module_as_main
"main", mod_spec)
File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\runpy.py", line 85, in run_code
exec(code, run_globals)
File "C:\Users\Sirius B\AppData\Roaming\Python\Python37\Scripts\jupyter-kernelspec.EXE_main.py", line 9, in
File "C:\Users\Sirius B\AppData\Roaming\Python\Python37\site-packages\traitlets\config\application.py", line 664, in launch_instance
app.start()
File "C:\Users\Sirius B\AppData\Roaming\Python\Python37\site-packages\jupyter_client\kernelspecapp.py", line 273, in start
return self.subapp.start()
File "C:\Users\Sirius B\AppData\Roaming\Python\Python37\site-packages\jupyter_client\kernelspecapp.py", line 143, in start
replace=self.replace,
File "C:\Users\Sirius B\AppData\Roaming\Python\Python37\site-packages\jupyter_client\kernelspec.py", line 346, in install_kernel_spec
shutil.copytree(source_dir, destination)
File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\shutil.py", line 318, in copytree
names = os.listdir(src)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\Users\Sirius'
```

**Expected behavior**
IQ# should install correctly.

**System information**
 - OS: Windows
 - Browser N/A
 - Version
    - Windows 10
    - Python 3.8
    - QDK 0.10

**Comment by rmshaffer** [comment]
Tested and verified that this works correctly on recent builds, presumably fixed by https://github.com/microsoft/jupyter-core/pull/40. Closing.

**Comment by ayed42** [comment]
g
